### PR TITLE
chore(package.json): Move jump.js from devDeps to deps on package.json

### PR DESCRIPTION
**Pull request by brnrdog**
chore(package.json): Move jump.js from devDeps to deps on package.json

Jump.js should be listed as a true dependency instead of a dev dependency.

### CODE REVIEW

**Comment by leandrogrillo** [comment]
nice @brnrdog :)

just a little thing about this pr, commit message following our standard. You can read more how we write messages in [contribution section](https://github.com/leroy-merlin-br/garden/blob/master/CONTRIBUTING.md)

**Comment by brnrdog** [comment]
Sure, just updated it @leandrogrillo 😉

**Comment by rands0n** [comment]
I think this message `chore(package.json): Move jump.js from devDeps to deps on package.json` is the commit message. Could you make an ammend and make a `push -f`?

**Comment by leandrogrillo** [comment]
ty @brnrdog :)

**Pull request merged**
